// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace WechatPTM.Model.BizEntity
{
	[Alias("CouponTrack")]
    public partial class CouponTrack 
    {
        [Required]
        public int BrandID { get; set;}
        [Required]
        public string WechatID { get; set;}
        [Required]
        public long SceneID { get; set;}
        [Required]
        public long CouponID { get; set;}
        [Required]
        public long ID { get; set;}
        public string OpenID { get; set;}
        public DateTime? SendTIme { get; set;}
        public DateTime? RedempTime { get; set;}
        public int? Status { get; set;}
    }
}
#pragma warning restore 1591
