// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace WechatPTM.Model.BizEntity
{
	[Alias("OrgnizationNodes")]
    public partial class OrgnizationNode 
    {
        [Required]
        public int BrandID { get; set;}
        [Required]
        public int OrgType { get; set;}
        [Required]
        public int OrgLevel { get; set;}
        public string OrgName { get; set;}
        public string OrgUserID { get; set;}
        [Required]
        public int OrgID { get; set;}
        [Required]
        public int ParentOrgID { get; set;}
        public string Desp { get; set;}
        public string CreateUser { get; set;}
        public DateTime? CreateDate { get; set;}
        public string UpdateUser { get; set;}
        public DateTime? UpdateDate { get; set;}
    }
}
#pragma warning restore 1591
