




















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `WechatMS`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `server=COOKERJIN_WIN8\MSSQL2012;database=WechatMS;uid=sa;pwd=sa123456`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`

