// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace WechatPTM.Model.BizEntity
{
	[Alias("ProductShow")]
    public partial class ProductShow 
    {
        [Required]
        public int BrandID { get; set;}
        [Required]
        public string SKU { get; set;}
        [Required]
        public int 序号 { get; set;}
        public string Title { get; set;}
        public string ImageUrl { get; set;}
        public byte[] Image { get; set;}
        public int? Type { get; set;}
        public int? ActFlag { get; set;}
        public string CreateUser { get; set;}
        public DateTime? CreateDate { get; set;}
        public string UpdateUser { get; set;}
        public DateTime? UpdateDate { get; set;}
    }
}
#pragma warning restore 1591
