// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace WechatPTM.Model.BizEntity
{
	[Alias("Store")]
    public partial class Store 
    {
        [Required]
        public int BrandID { get; set;}
        [AutoIncrement]
        public int StoreID { get; set;}
        public int? StoreTypeID { get; set;}
        public string StoreUserID { get; set;}
        public string StoreName { get; set;}
        public int? StoreType { get; set;}
        public DateTime? OpenDate { get; set;}
        public DateTime? CloseDate { get; set;}
        public byte? StoreStatus { get; set;}
        public string Address { get; set;}
        public double? Location_X { get; set;}
        public double? Location_Y { get; set;}
        public string ZipCode { get; set;}
        public string Telephone { get; set;}
        public string Fax { get; set;}
        public string Email { get; set;}
        public string Remark { get; set;}
        public string CreateUser { get; set;}
        public DateTime? CreateDate { get; set;}
        public string UpdateUser { get; set;}
        public DateTime? UpdateDate { get; set;}
    }
}
#pragma warning restore 1591
