// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace WechatPTM.Model.BizEntity
{
	[Alias("SYSTEMPARAMS")]
    public partial class SYSTEMPARAM 
    {
        [AutoIncrement]
		[PrimaryKey]
        public int ID { get; set;}
        public int? BrandID { get; set;}
        public string Param { get; set;}
        public string ParamName { get; set;}
        public string Value { get; set;}
        public string CreateUser { get; set;}
        public DateTime? CreateTime { get; set;}
        public string UpdateUser { get; set;}
        public DateTime? UpdateTime { get; set;}
    }
}
#pragma warning restore 1591
